# Changes here will be overwritten by Copier
_commit: '9689455'
_src_path: https://github.com/python-project-templates/base.git
add_extension: python
email: t.paine154@gmail.com
github: airflow-laminar
project_description: Airflow utilities for configuration of many DAGs and DAG environments
project_name: airflow config
python_version_primary: '3.11'
team: the airflow-config authors
