name: Build Status

on:
  push:
    branches:
      - main
    tags:
      - v*
    paths-ignore:
      - LICENSE
      - README.md
  pull_request:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

permissions:
  contents: read
  checks: write
  pull-requests: write

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: ["3.11"]
        airflow-version: ["2.8.1", "2.9.2", "2.10.4"]

    steps:
    - uses: actions/checkout@v4

    - uses: actions-ext/python/setup@main
      with:
        version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: make develop

    - name: Install airflow
      run: uv pip install -U apache-airflow==${{ matrix.airflow-version }} apache-airflow-providers-ssh

    - name: Lint
      run: make lint

    - name: Checks
      run: make checks

    - name: Build
      run: make build

    - name: Test
      run: make coverage

    - name: Upload test results (Python)
      uses: actions/upload-artifact@v4
      with:
        name: test-results-${{ matrix.os }}-${{ matrix.python-version }}-${{ matrix.airflow-version }}
        path: junit.xml
      if: ${{ always() }}

    - name: Publish Unit Test Results
      uses: EnricoMi/publish-unit-test-result-action@v2
      with:
        files: '**/junit.xml'
      if: matrix.airflow-version == '2.10.4'

    - name: Upload coverage
      uses: codecov/codecov-action@v5
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
      if: matrix.airflow-version == '2.10.4'

    - name: Make dist
      run: make dist

    - uses: actions/upload-artifact@v4
      with:
        name: dist-${{matrix.os}}
        path: dist
      if: matrix.airflow-version == '2.10.4'
